version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: 3313
      POSTGRES_DB: course 
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    ports:
      - '3000:3000'
