version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: 3313
      POSTGRES_DB: course 
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
